<?php
// Copyright 1999-2015. Parallels IP Holdings GmbH.
?>
<?php //echo $this->renderTabs($this->tabs); ?>

<?php if ($this->key): ?>
	Status: Active
<?php endif ?>

<?php echo $this->form; ?>

<?php if (!isset($this->key)): ?>
	<br/><br/><br/>
	<h3>Activation Instructions</h3>
	<p>To activate SIDEKICK for Plesk, please enter the SIDEKICK API credentials you received when you opened your account above. </p>
	<p>If you have misplaced your API Credentials, please contact us at <a href='mailto:support@sidekick.pro'>support@sidekick.pro</a>. </p>

	<br/>
	<h3>Purchasing a Plesk for SIDEKICK license or licenses</h3>
	<p>If you would like to purchase SIDEKICK for Plesk or arrange a free demo, please visit <a href='http://www.sidekick.pro/plesk-extension'>http://www.sidekick.pro/plesk-extension</a> or contact <a href='mailto:sales@sidekick.pro'>sales@sidekick.pro</a> </p>

	<br/>
	<h3>Deploy Plesk Automatically with Every Installation</h3>
	<p>Through some simple bash scripting you can utilize the Plesk API to install and activate the SIDEKICK extension.</p>

	<p>
		<pre>
/usr/local/psa/bin/extension -i <b>sidekick_extension.zip</b>;
plesk php /usr/local/psa/admin/plib/modules/sidekick/scripts/configure.php <b>sidekick_api_email sidekick_api_password</b>;	</pre>
		</p>

		<b>Example</b>
		<p>
			<pre>
/usr/local/psa/bin/extension -i <b>/mnt/hgfs/dist/sidekick_plesk_extension.zip</b>;
plesk php /usr/local/psa/admin/plib/modules/sidekick/scripts/configure.php <b>me@yourmail.com me@yourmail.com</b>;</pre>
			</p>

	<br/>		
	<h3>For Advanced Mass Deployments</h3>
	<p>For advanced installations you can directly call the SIDEKICK API to authenticate and generate a new key. </p>
	<p><b>Read these articles:</b></p>

	<ol>
		<li>API Authentication - <a target='_blank' href='https://sidekick.zendesk.com/hc/en-us/articles/208566047-API-Authentication'>https://sidekick.zendesk.com/hc/en-us/articles/208566047-API-Authentication</a></li>
		<li>Key Generation - <a target='_blank' href='https://sidekick.zendesk.com/hc/en-us/articles/207839558-Generate-Activation-Key-via-API'>https://sidekick.zendesk.com/hc/en-us/articles/207839558-Generate-Activation-Key-via-API</a></li>
		<li>Plesk Configuration - <a target='_blank' href='https://sidekick.zendesk.com/hc/en-us/articles/209973987'>https://sidekick.zendesk.com/hc/en-us/articles/209973987</a></li>
	</ol>

<?php endif ?>

