<?php echo $this->buy_link ?>

<?php if (!$this->toolkit_not_there): ?>
	<?php if (!$this->wp_installs): ?>
		There is no WordPress installations to install Sidekick on.
	<?php elseif (!$this->licenses): ?>
		You need to installa a SIDEKICK license to activate WordPress installs.

		<br/><br/>
		Once your license is installed you will have the ability to install SIDEKCIK on individual WordPress installations. Those installations will get the full Walkthrough library activated.

		<br/>

		To buy a license you need to visit <a href='https://go.plesk.com/buy-plesk-ext/sidekick' target='_blank'>this link</a>.

	<?php else: ?>
		Select the WordPress domains you would like to activate SIDEKICK on. <br/><br/>
		Those installations will get the full Walkthrough library activated.
<br/>

		<?php echo $this->form; ?>
	<?php endif; ?>
<?php endif; ?>
