<?php

// var_dump($this->wp_installs);

?>
<?php echo $this->form; ?>
<!-- <form method='POST' action='/modules/sidekick/'>
<div id="customer-service-plan-list-container">
    <div id="gen-id-867336" class="actions-box">
        <div class="r-actions">
            <ul class="r-actions-list">
                <li class="r-actions-item r-actions-select"><span></span>
                </li>
                <li class="r-actions-item r-actions-toolbar" onclick="Jsw.getComponent('gen-id-867336').onResponsiveButtonClick(event, 'toolbar');"><span></span>
                </li>
                <li class="r-actions-item r-actions-search" onclick="Jsw.getComponent('gen-id-867336').onResponsiveButtonClick(event, 'search');"><span></span>
                </li>
            </ul>
        </div>
        <div id="customer-service-plan-list-operations" class="objects-toolbar clearfix">
            <a id="buttonAddNewPlan" class="s-btn sb-add-new-plan" href="/admin/customer-service-plan/create">
                <i><i><i><span>Activate Sidekick</span></i></i></i>
            </a>
            <a id="buttonDuplicatePlans" class="s-btn sb-copy-selected" href="javascript:;"><i><i><i><span>Deactivate</span></i></i></i>
            </a>
        </div>
    </div>
    <div class="list">
        <table id="customer-service-plan-list-table" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th class="select">
                        <input type="checkbox" class="checkbox" name="listGlobalCheckbox">
                    </th>
                    <th class="sort"><a class="sort-up">WordPress Install</a>
                    </th>
                    <th><a>Action</a>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr class=" odd" data-row-id="3">
                    <td class="select">
                        <input type="checkbox" class="checkbox" name="listCheckbox[]" value="3">
                    </td>
                    <td class=""><span><a href="/admin/customer-service-plan/edit/id/3">Default Domain</a></span>
                    </td>

                    <td class=""></td>
                </tr>

            </tbody>
        </table>
    </div>

    <p class="js-empty-list empty-list text-muted" style="display: none;">No items found.</p>
</div>
</form> -->
